from settings.common import *  # noqa: F401, F403

DEBUG = False

SECURE_PROXY_SSL_HEADER = "HTTP_X_FORWARDED_PROTO", "https"
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 604800
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
