version: "3.8"

services:
  database:
    platform: linux/amd64
    image: postgres:15.2
    environment:
      POSTGRES_USER: {{cookiecutter.project_name}}
      POSTGRES_DB: {{cookiecutter.project_name}}
      POSTGRES_PASSWORD: M6hzeBBQxdNi4eYVY6GD
    volumes:
      - {{cookiecutter.project_name}}-pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  webserver:
    platform: linux/amd64
    env_file:
      - .environ
    depends_on:
      - database
    build:
      context: .
    environment:
      - PGHOST=database
      - PGUSER={{cookiecutter.project_name}}
      - PGPASSWORD=M6hzeBBQxdNi4eYVY6GD
    ports:
      - "8000:8000"

volumes:
  {{cookiecutter.project_name}}-pgdata:
