[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py310"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "TESTS"]

[tool.mypy]
ignore_missing_imports = true
strict_optional = false
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = "-vv --reuse-db"
testpaths = "tests"

[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
license = "Proprietary"
authors = [
    "{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>",
]

packages = [
    {include = "home", from = "src"},
    {include = "lib", from = "src"},
    {include = "registration", from = "src"},
    {include = "settings", from = "src"},
    {include = "asgi.py", from = "src"},
    {include = "urls.py", from = "src"},
    {include = "wsgi.py", from = "src"},
]


[tool.poetry.dependencies]
# python version
python = "^3.10.0"

# dependencies
dj-settings = "~3.0.0"
Django = "~4.0.0"
django-grappelli = "~3.0.0"
gunicorn = "~20.1.0"
pathurl = "~0.5.0"
psycopg2 = "~2.9.0"
uvicorn = "~0.18.0"

[tool.poetry.dev-dependencies]
black = "~22.6.0"
django-extensions = "~3.2.0"
factory-boy = "~3.2.0"
flake8 = "~4.0.0"
flake8-bugbear = "~22.7.0"
flake8-builtins = "~1.5.0"
flake8-comprehensions = "~3.10.0"
flake8-eradicate = "~1.2.0"
flake8-executable = "~2.1.0"
flake8-mutable = "~1.2.0"
flake8-tidy-imports = "~4.8.0"
isort = "~5.10.0"
mypy = "~0.971"
pdbpp = "~0.10.0"
pipdeptree = "~2.2.0"
ptpython = "~3.0.0"
pytest = "~7.1.0"
pytest-django = "~4.5.0"
Werkzeug = "~2.1.0"
