[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py39"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "TESTS"]

[tool.mypy]
ignore_missing_imports = true
strict_optional = false
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = "-vv --reuse-db"
testpaths = "tests"

[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
license = "Proprietary"
authors = [
    "{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>",
]

packages = [
    {include = "lib", from = "src"},
    {include = "settings", from = "src"},
    {include = "asgi.py", from = "src"},
    {include = "urls.py", from = "src"},
    {include = "wsgi.py", from = "src"},
]


[tool.poetry.dependencies]
python = "^3.9.0"

django = "~3.2.0"
gunicorn = "~20.1.0"
psycopg2 = "~2.9.0"
yashiro = "~0.6.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.0"
mypy = "^0.910"

pytest = "^6.2.0"
pytest-django = "^4.4.0"
factory_boy = "^3.2.0"

ipython = "^7.27.0"
ipdb = "^0.13.0"

django-extensions = "^3.2.0"
werkzeug = "^2.0.0"

flake8 = "^3.9.0"
flake8-bugbear = "^21.9.0"
flake8-builtins = "^1.5.0"
flake8-comprehensions = "^3.6.0"
flake8-eradicate = "^1.1.0"
flake8-executable = "^2.1.0"
flake8-mutable = "^1.2.0"
flake8-tidy-imports = "^4.4.0"
