[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py36", "py37", "py38"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "TESTS"]

[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
authors = [
    "{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>",
]

[tool.poetry.dependencies]
python = "^3.6"

django = "~3.0"
gunicorn = "~20.0"
psycopg2 = "~2.8"
yashiro = "~0.3"


[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
isort = "^4.3"

django-extensions = "^2.1"
werkzeug = "^0.16"

pytest = "^5.1"
pytest-cov = "^2.8"
pytest-django = "^3.5"
factory_boy = "^2.12"

ipython = "^7.10"
ipdb = "^0.12"

flake8 = "^3.7"
flake8-bugbear = "^19.8"
flake8-builtins = "^1.4"
flake8-comprehensions = "^3.1"
flake8-eradicate = "^0.2.3"
flake8-executable = "^2.0"
flake8-mutable = "^1.2"
flake8-tidy-imports = "^3.1"
