[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py38"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "TESTS"]

[tool.coverage.run]
source = ["src/"]
omit = ["*/template*", "src/wsgi.py"]

[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
authors = [
    "{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>",
]

[tool.poetry.dependencies]
python = "^3.8.0"

django = "~3.1.0"
gunicorn = "~20.0.0"
psycopg2 = "~2.8.0"
yashiro = "~0.3.0"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
isort = "^5.6.0"

pytest = "^6.1.0"
pytest-cov = "^2.10.0"
pytest-django = "^4.1.0"
factory_boy = "^3.0.0"

ipython = "^7.18.0"
ipdb = "^0.13.0"

django-extensions = "^3.0.0"
werkzeug = "^1.0.0"

flake8 = "^3.8.0"
flake8-bugbear = "^20.11.0"
flake8-builtins = "^1.5.0"
flake8-comprehensions = "^3.3.0"
flake8-eradicate = "^1.0.0"
flake8-executable = "^2.1.0"
flake8-mutable = "^1.2.0"
flake8-tidy-imports = "^4.1.0"
